[y1,fs]=audioread('noisy_female_white_0.wav');
[y2,  ]=audioread('denoised_female_white_0.wav');
t1=1/fs:1/fs:length(y1)/fs;
t2=1/fs:1/fs:length(y2)/fs;
figure(1);
subplot(2,1,1);
plot(t1,y1);
xlabel('t/s');
ylabel('y1');
title('Noisy Female Speech (White Noise, 0dB)');
subplot(2,1,2);
plot(t2,y2);
xlabel('t/s');
ylabel('y2');
title('Denoised Female Speech (White Noise, 0dB)');

[y1,fs]=audioread('noisy_female_white_20.wav');
[y2,  ]=audioread('denoised_female_white_20.wav');
t1=1/fs:1/fs:length(y1)/fs;
t2=1/fs:1/fs:length(y2)/fs;
figure(2);
subplot(2,1,1);
plot(t1,y1);
xlabel('t/s');
ylabel('y1');
title('Noisy Female Speech (White Noise, 20dB)');
subplot(2,1,2);
plot(t2,y2);
xlabel('t/s');
ylabel('y2');
title('Denoised Female Speech (White Noise, 20dB)');